/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Créer un compte utilisateur */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Compte créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Adresse e-mail déjà utilisée */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Se connecter */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Authentification réussie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Récupérer le profil de l'utilisateur connecté */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profil utilisateur */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modifier son mot de passe
         * @description Change le mot de passe de l'utilisateur connecté. L'ancien mot de passe est exigé.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description Mot de passe modifié */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les utilisateurs
         * @description Réservé aux administrateurs.
         */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                    role?: components["schemas"]["UserRole"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste paginée des utilisateurs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedUsers"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulter un utilisateur */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Utilisateur */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Supprimer un utilisateur */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Utilisateur supprimé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Modifier un utilisateur */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdateRequest"];
                };
            };
            responses: {
                /** @description Utilisateur modifié */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rechercher et lister les salles */
        get: {
            parameters: {
                query?: {
                    /** @description Recherche par nom ou description */
                    search?: string;
                    location?: string;
                    capacityMin?: number;
                    capacityMax?: number;
                    /** @description Date recherchée au format YYYY-MM-DD */
                    date?: string;
                    startTime?: string;
                    endTime?: string;
                    available?: boolean;
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des salles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedRooms"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        /**
         * Ajouter une salle
         * @description Réservé aux propriétaires/gestionnaires et administrateurs.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoomCreateRequest"];
                };
            };
            responses: {
                /** @description Salle créée */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Room"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulter les détails d'une salle */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Détails de la salle */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Room"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Supprimer une salle
         * @description Réservé au gestionnaire propriétaire de la salle et aux administrateurs.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Salle supprimée */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Modifier une salle
         * @description Réservé au gestionnaire propriétaire de la salle et aux administrateurs.
         *     Modification partielle : seuls les champs envoyés sont modifiés.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoomUpdateRequest"];
                };
            };
            responses: {
                /** @description Salle modifiée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Room"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/rooms/{roomId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        /** Consulter les disponibilités d'une salle */
        get: {
            parameters: {
                query: {
                    date: string;
                    startTime?: string;
                    endTime?: string;
                };
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Créneaux disponibles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AvailabilitySlot"][];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Définir les disponibilités d'une salle
         * @description Réservé au gestionnaire propriétaire de la salle et aux administrateurs.
         *     Remplace l'ensemble des créneaux de la date indiquée.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: components["parameters"]["RoomId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AvailabilityUpdateRequest"];
                };
            };
            responses: {
                /** @description Disponibilités mises à jour */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AvailabilitySlot"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulter ses réservations
         * @description Renvoie uniquement les réservations de l'utilisateur connecté, y compris
         *     celles au statut CANCELLED. Les filtres `from` et `to` portent sur la date
         *     de début (`startAt`) et sont inclusifs.
         */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["ReservationStatus"];
                    /** @description Réservations dont `startAt` est à partir de cette date (incluse) */
                    from?: string;
                    /** @description Réservations dont `startAt` est jusqu'à cette date (incluse) */
                    to?: string;
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des réservations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedReservations"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Réserver une salle
         * @description Vérifie la disponibilité avant de créer la réservation.
         *     La réservation est créée au statut PENDING, puis passe à CONFIRMED ou
         *     REJECTED via `/confirm` ou `/reject`. `startAt` doit être strictement
         *     antérieur à `endAt`, et `numberOfParticipants` ne doit pas dépasser la
         *     capacité de la salle (sinon 400).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReservationCreateRequest"];
                };
            };
            responses: {
                /** @description Réservation créée */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reservation"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{reservationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulter une réservation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reservationId: components["parameters"]["ReservationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Réservation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reservation"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Annuler une réservation
         * @description Annulation logique : la réservation n'est pas supprimée, elle passe au
         *     statut CANCELLED et reste consultable. Seules les réservations PENDING ou
         *     CONFIRMED peuvent être annulées (sinon 409).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reservationId: components["parameters"]["ReservationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Réservation annulée (statut CANCELLED) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Modifier une réservation
         * @description Seules les réservations PENDING ou CONFIRMED peuvent être modifiées (sinon 409).
         *     Une modification du créneau d'une réservation CONFIRMED la repasse à PENDING.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reservationId: components["parameters"]["ReservationId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReservationUpdateRequest"];
                };
            };
            responses: {
                /** @description Réservation modifiée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reservation"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Nouveau créneau indisponible ou réservation non modifiable dans son statut actuel */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/reservations/{reservationId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmer une réservation
         * @description Utilisé par le gestionnaire de la salle ou un administrateur lorsque la validation est requise.
         *     Seule une réservation au statut PENDING peut être confirmée (sinon 409).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reservationId: components["parameters"]["ReservationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Réservation confirmée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "00000000-0000-4000-8000-300000000001",
                         *       "roomId": "00000000-0000-4000-8000-100000000001",
                         *       "userId": "00000000-0000-4000-8000-200000000001",
                         *       "startAt": "2026-10-12T09:00:00Z",
                         *       "endAt": "2026-10-12T12:00:00Z",
                         *       "status": "CONFIRMED",
                         *       "totalAmount": 135
                         *     }
                         */
                        "application/json": components["schemas"]["Reservation"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{reservationId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refuser une réservation
         * @description Utilisé par le gestionnaire de la salle ou un administrateur.
         *     Seule une réservation au statut PENDING peut être refusée (sinon 409).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reservationId: components["parameters"]["ReservationId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ReservationRejectRequest"];
                };
            };
            responses: {
                /** @description Réservation refusée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "00000000-0000-4000-8000-300000000001",
                         *       "roomId": "00000000-0000-4000-8000-100000000001",
                         *       "userId": "00000000-0000-4000-8000-200000000001",
                         *       "startAt": "2026-10-12T09:00:00Z",
                         *       "endAt": "2026-10-12T12:00:00Z",
                         *       "status": "REJECTED",
                         *       "totalAmount": 135
                         *     }
                         */
                        "application/json": components["schemas"]["Reservation"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initier le paiement d'une réservation
         * @description Réservé au client auteur de la réservation.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PaymentCreateRequest"];
                };
            };
            responses: {
                /** @description Paiement initié */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulter le statut d'un paiement */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    paymentId: components["parameters"]["PaymentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paiement */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gérer toutes les réservations
         * @description Réservé aux administrateurs.
         */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["ReservationStatus"];
                    roomId?: string;
                    userId?: string;
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Réservations administratives */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedReservations"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulter les statistiques
         * @description Réservé aux administrateurs.
         */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistiques de la plateforme */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Statistics"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        UserRole: "CLIENT" | "GESTIONNAIRE" | "ADMINISTRATEUR";
        User: {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Format: date-time */
            createdAt?: string;
        };
        RegisterRequest: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResponse: {
            accessToken: string;
            refreshToken?: string;
            /** @example 3600 */
            expiresIn?: number;
            user: components["schemas"]["User"];
        };
        ChangePasswordRequest: {
            /** Format: password */
            currentPassword: string;
            /** Format: password */
            newPassword: string;
        };
        UserUpdateRequest: {
            firstName?: string;
            lastName?: string;
            /** Format: email */
            email?: string;
            role?: components["schemas"]["UserRole"];
        };
        Room: {
            /** Format: uuid */
            id: string;
            /** @example Salle Paris */
            name: string;
            description?: string;
            /** @example 20 */
            capacity: number;
            /** @example Paris */
            location: string;
            /**
             * @example [
             *       "Wi-Fi",
             *       "Vidéoprojecteur",
             *       "Tableau blanc"
             *     ]
             */
            equipment?: string[];
            /**
             * Format: double
             * @example 35
             */
            pricePerHour: number;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            /** Format: uuid */
            ownerId?: string;
            /** Format: uri */
            imageUrl?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        RoomCreateRequest: {
            name: string;
            description?: string;
            capacity: number;
            location: string;
            equipment?: string[];
            /** Format: double */
            pricePerHour: number;
            /** Format: uri */
            imageUrl?: string;
        };
        RoomUpdateRequest: {
            name?: string;
            description?: string;
            capacity?: number;
            location?: string;
            equipment?: string[];
            /** Format: double */
            pricePerHour?: number;
            /** Format: uri */
            imageUrl?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
        };
        AvailabilitySlot: {
            /** Format: time */
            startTime: string;
            /** Format: time */
            endTime: string;
            available: boolean;
        };
        AvailabilityUpdateRequest: {
            /** Format: date */
            date: string;
            slots: components["schemas"]["AvailabilitySlot"][];
        };
        /**
         * @description Cycle de vie : PENDING à la création, puis CONFIRMED ou REJECTED (gestionnaire/admin).
         *     PENDING ou CONFIRMED peut passer à CANCELLED (annulation).
         *     CONFIRMED passe à COMPLETED automatiquement une fois `endAt` dépassé.
         * @enum {string}
         */
        ReservationStatus: "PENDING" | "CONFIRMED" | "REJECTED" | "CANCELLED" | "COMPLETED";
        Reservation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            roomId: string;
            /** Format: uuid */
            userId: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            status: components["schemas"]["ReservationStatus"];
            numberOfParticipants?: number;
            comment?: string;
            /** Format: double */
            totalAmount: number;
            /** @example EUR */
            currency?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ReservationCreateRequest: {
            /** Format: uuid */
            roomId: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            numberOfParticipants?: number;
            comment?: string;
        };
        ReservationUpdateRequest: {
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            numberOfParticipants?: number;
            comment?: string;
        };
        ReservationRejectRequest: {
            reason?: string;
        };
        Payment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            reservationId: string;
            /** Format: double */
            amount: number;
            /** @example EUR */
            currency: string;
            /** @enum {string} */
            status: "PENDING" | "PAID" | "FAILED" | "REFUNDED";
            /** Format: uri */
            paymentUrl?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PaymentCreateRequest: {
            /** Format: uuid */
            reservationId: string;
            /** @enum {string} */
            paymentMethod: "CARD" | "PAYPAL";
        };
        Statistics: {
            totalUsers?: number;
            totalRooms?: number;
            totalReservations?: number;
            confirmedReservations?: number;
            cancelledReservations?: number;
            /** Format: double */
            totalRevenue?: number;
        };
        PaginatedUsers: {
            items?: components["schemas"]["User"][];
            page?: number;
            pageSize?: number;
            total?: number;
        };
        PaginatedRooms: {
            items?: components["schemas"]["Room"][];
            page?: number;
            pageSize?: number;
            total?: number;
        };
        PaginatedReservations: {
            items: components["schemas"]["Reservation"][];
            page: number;
            pageSize: number;
            total: number;
        };
        Error: {
            /** @example VALIDATION_ERROR */
            code?: string;
            /** @example Les données fournies sont invalides. */
            message?: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Requête invalide */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentification requise ou invalide */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Accès interdit */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ressource introuvable */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflit avec l'état actuel de la ressource (créneau indisponible, statut incompatible) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        UserId: string;
        RoomId: string;
        ReservationId: string;
        PaymentId: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
