// Package core : rempli ensemble en séance 2
// (types générés depuis openapi.yml, client HTTP typé, règles métier, schémas Zod).
export {};

import createClient from "openapi-fetch";
import type { paths } from "./api/schema"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "http://host.docker.internal:4010" });

const {
  // only present if 2XX response
  data,
  // only present if 4XX or 5XX response
  error,
} = await client.GET("/rooms");

if (!data) {
  throw new Error(`Erreur API : ${JSON.stringify(error)}`);
}
console.log(data, error);